interface CImgWASM8Bit {
  void CImgWASM8Bit();
  void CImgWASM8Bit(unsigned short x, optional unsigned short y, optional unsigned short z, optional unsigned short c);
  
  [Value] static CImgWASM8Bit fromFile([Const] DOMString filename);

  void fill(octet val, optional octet val2, optional octet val3, optional octet val4);
  void fillC(unsigned short x, unsigned short y, unsigned short z, octet c1, optional octet c2, optional octet c3);
  
  long height();
  long width();
  long size();
};
